# Generated by Django 4.2.2 on 2023-06-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metodo_de_pago', '0002_alumnos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alumnos',
        ),
    ]
