# Generated by Django 4.1.7 on 2023-05-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suelo', models.CharField(max_length=45)),
                ('Cantidad', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Producto', models.CharField(max_length=45)),
                ('Descripcion', models.CharField(max_length=45)),
                ('Stock', models.IntegerField()),
                ('Precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Cant_participante', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('Productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportHub.productos')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportHub.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion_Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Horarios', models.DateField()),
                ('Cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportHub.cancha')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportHub.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomYApell', models.CharField(max_length=30)),
                ('Domicilio', models.CharField(max_length=30)),
                ('DNI', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('Fecha_Nac', models.DateField()),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportHub.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel_Tenis', models.CharField(max_length=10)),
                ('Desafio', models.BooleanField()),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportHub.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportHub.torneo')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportHub.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Factura', models.IntegerField()),
                ('Ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportHub.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Canchas_Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Canchas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportHub.cancha')),
                ('Torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportHub.torneo')),
            ],
        ),
    ]
